#!/bin/bash

# A simple script to add 2 co-authors to git commits.

# To use:

# Copy mob to a directory in your $PATH
# run chmod +x mob
# Export the co-authors details - ie

# export MOBBER_1=Joe Bloggs <joe.bloggs@engineerbetter.com>
# export MOBBER_1=Jane Bloggs <jane.bloggs@engineerbetter.com>
# Once set, run mob your commit message to make a commit with the 2 co-authors included.

example="Joe Bloggs <joe.bloggs@engineerbetter.com>"

if [[ ! $MOBBER_1 ]]; then
    echo "Please export MOBBER_1 eg. 'export MOBBER_1=$example'"
    exit 0
fi
if [[ ! $MOBBER_2 ]]; then
    echo "Please export MOBBER_2 eg 'export MOBBER_2=$example'"
    exit 0
fi

commit_message=$*

echo "$commit_message"
echo
echo Co-authored-by: "$MOBBER_1"
echo Co-authored-by: "$MOBBER_2"
echo
echo "Commit this? (Yes/No) "
read -r response

case $response in
y|Y|YES|yes)
git commit -m "$commit_message

Co-authored-by: $MOBBER_1
Co-authored-by: $MOBBER_2";;

n|NO|N|no)
exit 0 ;;
esac
